layout_spectrum: 0
color:
  saturation: 0.1483674
  lightness: 0.797853
  brandStrength: 0.8412834
  brandColors:
    - '#55C1B4'
    - '#FAAF40'
    - '#A6A295'
    - '#3A3934'
    - '#010101'
  rhythmicContrast: 0.9397678
typography_spectrum: 0.3387097
name: PetMio
